@startuml

actor "Home Cook" as HC

rectangle "Recipe Assistant" {

    (Browse recipes)
    (Search recipes)
    (Open recipe)

}

HC --> (Browse recipes)
HC --> (Search recipes)
HC --> (Open recipe)

@enduml